// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SumaryYoutubeBackend.dbContext;

#nullable disable

namespace SumaryYoutubeBackend.Migrations
{
    [DbContext(typeof(SumaryYoutubeDbContext))]
    [Migration("20260306233304_MigrationSumary")]
    partial class MigrationSumary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SumaryYoutubeBackend.Models.VideoSummary", b =>
                {
                    b.Property<int>("IdVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVideo"));

                    b.Property<int>("CodeVideoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreateSumary")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MindMap")
                        .HasColumnType("text");

                    b.Property<string>("TextGemini")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnaiUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdVideo");

                    b.ToTable("VideoSummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
