// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SumaryYoutubeBackend.dbContext;

#nullable disable

namespace SumaryYoutubeBackend.Migrations
{
    [DbContext(typeof(SumaryYoutubeDbContext))]
    [Migration("20260406233828_AddDurationAndViewCountToVideo")]
    partial class AddDurationAndViewCountToVideo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SumaryYoutubeBackend.Models.AuthUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuthUsers");
                });

            modelBuilder.Entity("SumaryYoutubeBackend.Models.VideoSummary", b =>
                {
                    b.Property<int>("IdVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVideo"));

                    b.Property<string>("CodeVideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreateSumary")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("MindMap")
                        .HasColumnType("text");

                    b.Property<string>("TextGemini")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnaiUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Vizualization")
                        .HasColumnType("bigint");

                    b.HasKey("IdVideo");

                    b.HasIndex("IdUser");

                    b.ToTable("VideoSummaries");
                });

            modelBuilder.Entity("SumaryYoutubeBackend.Models.VideoSummary", b =>
                {
                    b.HasOne("SumaryYoutubeBackend.Models.AuthUser", "AuthUser")
                        .WithMany("VideosUser")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("SumaryYoutubeBackend.Models.AuthUser", b =>
                {
                    b.Navigation("VideosUser");
                });
#pragma warning restore 612, 618
        }
    }
}
